import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api } from './api';
import './styles.css';

const date = () => { const d = new Date(); if (d.getHours() < 4) d.setDate(d.getDate() - 1); return `${String(d.getFullYear()).slice(-2)}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;
const screens = [['dashboard','▦','Dashboard'],['config','⚙','Configuration'],['transactions','▤','Transactions'],['hisab','₹','Hisab'],['final','✓','Run Final'],['service','◉','Service Status']];

function Login({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { onLogin(await api.login({ email, password })); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main className="login"><section><span className="logo">♛</span><p className="eyebrow">COBO CLOUD</p><h1>WhatsApp operations, anywhere.</h1><p>Sign in to manage your bot, game flow and daily Hisab from Android.</p></section><form onSubmit={submit}><h2>Sign in</h2><label>Email or mobile<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Signing in…' : 'Sign in to Cobo'}</button><small>Each account has its own WhatsApp session, groups and records.</small></form></main>;
}
function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('cobo.mobile.session') || 'null'));
  const [screen, setScreen] = useState('dashboard'); const [data, setData] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [businessDate] = useState(date());
  const token = session?.access_token;
  const logout = () => { localStorage.removeItem('cobo.mobile.session'); setSession(null); };
  const login = value => { localStorage.setItem('cobo.mobile.session', JSON.stringify(value)); setSession(value); };
  const load = async current => { if (!token) return; setLoading(true); setError(''); try { const result = current==='dashboard' ? await api.dashboard(token,businessDate) : current==='config' ? await api.config(token) : current==='transactions' ? await api.transactions(token,businessDate) : current==='hisab' ? await api.hisab(token,businessDate) : current==='final' ? await api.finalOptions(token) : await api.serviceStatus(token); setData(result || {}); } catch(e) { setError(e.message); if(e.status===401) logout(); } finally { setLoading(false); } };
  useEffect(()=>{ if(token) load(screen); },[token,screen]);
  if (!session) return <Login onLogin={login}/>;
  const content = screen==='dashboard' ? <Dashboard data={data}/> : screen==='config' ? <Config data={data} token={token} reload={()=>load('config')}/> : screen==='transactions' ? <Transactions data={data}/> : screen==='hisab' ? <Hisab data={data}/> : screen==='final' ? <Final data={data} token={token} reload={()=>load('final')}/> : <Service data={data} token={token} reload={()=>load('service')}/>;
  return <main className="app"><aside><div className="brand"><span>♛</span><div><b>{session.workspace_name || 'Cobo'}</b><small>Cloud workspace</small></div></div><nav>{screens.map(([id,icon,label])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><i>{icon}</i>{label}</button>)}</nav><button className="logout" onClick={logout}>↪ Sign out</button></aside><section className="content"><header><div><p className="eyebrow">COBO CLOUD</p><h1>{screens.find(item=>item[0]===screen)?.[2]}</h1></div><div className="header-right"><span className="date">{businessDate}</span><button className="refresh" onClick={()=>load(screen)}>↻ Refresh</button></div></header>{error&&<p className="error banner">{error}</p>}{loading?<p className="loading">Loading cloud data…</p>:content}</section></main>;
}
function Dashboard({ data }) { return <><div className="cards"><Card label="Total Play" value={money(data.total_play)}/><Card label="Total Win" value={money(data.total_win)}/><Card label="Input Groups" value={data.customers?.length || 0}/><Card label="Markets" value={data.markets?.length || 0}/></div><section className="panel"><h2>Latest accepted plays</h2>{(data.live_messages||[]).map(row=><article className="row" key={row.id}><b>{row.group}</b><span>{row.market}</span><strong>{money(row.total)}</strong></article>)||<p>No accepted play today.</p>}</section></> }
const Card=({label,value})=><article className="card"><small>{label}</small><strong>{value}</strong></article>;
function Config({ data, token, reload }) { const [raw,setRaw]=useState(''); useEffect(()=>setRaw(JSON.stringify(data.config || data, null, 2)),[data]); const save=async()=>{ try { await api.saveConfig(token,JSON.parse(raw)); reload(); } catch(e){ alert(e.message); } }; return <section className="panel"><h2>Same Cobo configuration</h2><p>Input groups, LD, overflow, market timing and Dynamic Timing are saved to your cloud workspace.</p><textarea value={raw} onChange={e=>setRaw(e.target.value)} spellCheck="false"/><button onClick={save}>Save Configuration</button></section>; }
function Transactions({data}) { return <section className="panel"><h2>Transactions</h2>{(data.transactions||[]).map(row=><article className="row" key={row.id}><b>{row.contact}</b><span>{row.market}</span><strong>{money(row.total)}</strong></article>)||<p>No transaction found for this date.</p>}</section>; }
function Hisab({data}) { return <section className="panel"><h2>Daily Hisab</h2>{(data.rows||data.hisab||[]).map(row=><article className="hisab" key={row.contact}><b>{row.contact}</b><span>Play {money(row.total_play)} · Win {money(row.total_win)}</span><strong>Balance {money(row.current_balance)}</strong></article>)||<p>Run Final ke baad customer-wise Hisab yahan save hoga.</p>}</section>; }
function Final({data,token,reload}) { const [group,setGroup]=useState(''); const [message,setMessage]=useState(''); const run=async()=>{try{const result=await api.runFinal(token,group);setMessage(result.message||'Run Final queued successfully.');reload();}catch(e){setMessage(e.message)}}; return <section className="panel"><h2>Run Final</h2><p>Selected output group tables first, then each input group ka date-wise final and progressive play summary.</p><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Select output group</option>{(data.output_groups||[]).map(name=><option key={name}>{name}</option>)}</select><button onClick={run} disabled={!group}>Run Final</button>{message&&<p className="notice">{message}</p>}</section>; }
function Service({data,token,reload}) { const [message,setMessage]=useState(''); const action=async name=>{try{const result=await api.serviceAction(token,name);setMessage(result.message||`${name} requested`);reload();}catch(e){setMessage(e.message)}}; return <section className="panel service"><p className={`status ${data.running?'up':'down'}`}>{data.running?'● Running':'● Stopped'}</p><h2>{data.whatsapp_status || 'WhatsApp service status'}</h2><p>Cloud server continues even when this Android app is closed.</p><div><button onClick={()=>action('start')}>▶ Start Service</button><button className="danger" onClick={()=>action('stop')}>■ Stop Service</button></div>{message&&<p className="notice">{message}</p>}</section>; }
createRoot(document.getElementById('root')).render(<App/>);
